### ISSUE TITLE
package ‘Riex’ is not available (for R version 3.5.2)

### ISSUE THREAD

**Issue by nocodehummel** [TheEliteAnalyst/Riex#2]
install.packages("Riex") is not working on containerized R with RStudio (rocker/rstudio-stable:latest).
Linux version is "x86_64-pc-linux-gnu (64-bit)".  Error message: "package ‘Riex’ is not available (for R version 3.5.2)."

I would like to try the package. Any suggestions?

**Comment by TheEliteAnalyst** [comment]
Thank you for your interest in using "Riex" and bringing this issue to my
attention.
I'll investigate and update you.

Best regards,
Myriam Ibrahim

**Comment by TheEliteAnalyst** [comment]
I would suggest updating R version to 3.5.2.3 and retry installing 'Riex'. Also, you might consider installing from GitHub directly - code below:
> install.packages("devtools")
> library(devtools)
> install_github("TheEliteAnalyst/Riex")
Hope that solve the issue.. Looking forward to your feedback and any suggestions you have.
Best regards,
Myriam  Ibrahim
![Riex_Install](https://user-images.githubusercontent.com/7199786/72670924-792bf380-3a11-11ea-9cd0-e51abba7fb14.PNG)

**Comment by nocodehummel** [comment]
Thank you for the proposed solution. That worked on my local environment.

**Comment by TheEliteAnalyst** [comment]
Perfect.. Looking forward to your feedback and suggestions!
Best regards,
Myriam

**Comment by TheEliteAnalyst** [comment]
Issue Closed. To resolve, user should upgrade to R version to 3.5.2.3 or above
