### ISSUE TITLE
error using iex.company

### ISSUE THREAD

**Issue by csetzkorn** [TheEliteAnalyst/Riex#3]
This:

```
library(Riex)
sk <- "sk_xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"
x <- "TSLA"
TSLA_Co <- iex.company(x, sk)
TSLA_Co
```

returns:

> Error: Column `address2` must be a 1d atomic vector or a list
> Call `rlang::last_error()` to see a backtrace
> Error: object 'TSLA_Co' not found

Any ideas?

**Comment by TheEliteAnalyst** [comment]
Hi Christian,
Regarding this error, can you please confirm you are using the secret key
from your IEX account.
Also, if you have any screenshots that you can share that will be greatly
helpful
Rgds - MI

**Comment by maurohamz** [comment]
Hi,
Having the exact same issue. 
Can confirm I'm using the secret key from my account.

Here is a screenshot with the error.

![iex_snap](https://user-images.githubusercontent.com/43419597/95606842-8c0fa980-0a20-11eb-80e9-7f262f98da68.PNG)

**Comment by TheEliteAnalyst** [comment]
Mauro,

Thank you for the feedback.. I'll check and update shortly on how to
resolve error.

Best,
Myriam

**Comment by marcomeola** [comment]
any solution here? Had the same problem

**Comment by TheEliteAnalyst** [comment]
@csetzkorn, @maurohamz  & @marcomeola 
To all - True apology for a delayed response to this issue. Updates made and pushed to GitHub, you can install the package directly  using the following steps till changes available on CRAN.
**Step 1**
`install.packages("devtools")`
**Step 2**
`library(devtools)
install_github("TheEliteAnalyst/Riex")`

Please feel free to forward any other suggestions you have so I can incorporate in next release.
Rgds - MI

**Comment by maurohamz** [comment]
Awesome, appreciate the effort. Will test shortly.
