### ISSUE TITLE
Error: All columns in a tibble must be vectors.

### ISSUE THREAD

**Issue by MislavSag** [TheEliteAnalyst/Riex#6]
The sample code:
```
library(Riex)
sk <- "KEY"
x <- "TSLA"
TSLA_Co <- iex.company(x, sk)
```
returns an error:
```
[1] "Stock Info is available in IEX"
Error: All columns in a tibble must be vectors.
x Column `employees` is NULL.
x Column `address2` is NULL.
Run `rlang::last_error()` to see where the error occurred.
```

**Comment by TheEliteAnalyst** [comment]
Mislav,
This issue was resolved in the version on Github - Null values will be
displayed as "NA". Changes will be reflected in next release to CRAN in
addition to other functionality.
Thank you again for the feedback!
Rgds - MI
[image: image.png]
